# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :development do
end

group :test do
    gem 'rspec'
    gem 'guard', '~> 2.15.0'
    gem 'guard-rspec', require: false
end

group :develompent, :test do
    gem 'byebug'
end
